/// Country dial codes for the phone number field's country picker.
/// Israel is intentionally excluded per product requirement.
/// This is a plain Dart list - add more rows any time if a country is missing.
class CountryDialCode {
  final String code;
  final String country;
  const CountryDialCode(this.code, this.country);
}

const List<CountryDialCode> kCountryDialCodes = [
  CountryDialCode('+20', 'Egypt'),
  CountryDialCode('+966', 'Saudi Arabia'),
  CountryDialCode('+971', 'UAE'),
  CountryDialCode('+965', 'Kuwait'),
  CountryDialCode('+973', 'Bahrain'),
  CountryDialCode('+974', 'Qatar'),
  CountryDialCode('+968', 'Oman'),
  CountryDialCode('+962', 'Jordan'),
  CountryDialCode('+961', 'Lebanon'),
  CountryDialCode('+963', 'Syria'),
  CountryDialCode('+964', 'Iraq'),
  CountryDialCode('+218', 'Libya'),
  CountryDialCode('+216', 'Tunisia'),
  CountryDialCode('+213', 'Algeria'),
  CountryDialCode('+212', 'Morocco'),
  CountryDialCode('+249', 'Sudan'),
  CountryDialCode('+252', 'Somalia'),
  CountryDialCode('+253', 'Djibouti'),
  CountryDialCode('+222', 'Mauritania'),
  CountryDialCode('+970', 'Palestine'),
  CountryDialCode('+90', 'Turkey'),
  CountryDialCode('+98', 'Iran'),
  CountryDialCode('+93', 'Afghanistan'),
  CountryDialCode('+92', 'Pakistan'),
  CountryDialCode('+91', 'India'),
  CountryDialCode('+880', 'Bangladesh'),
  CountryDialCode('+94', 'Sri Lanka'),
  CountryDialCode('+95', 'Myanmar'),
  CountryDialCode('+960', 'Maldives'),
  CountryDialCode('+977', 'Nepal'),
  CountryDialCode('+975', 'Bhutan'),
  CountryDialCode('+86', 'China'),
  CountryDialCode('+852', 'Hong Kong'),
  CountryDialCode('+853', 'Macau'),
  CountryDialCode('+886', 'Taiwan'),
  CountryDialCode('+81', 'Japan'),
  CountryDialCode('+82', 'South Korea'),
  CountryDialCode('+850', 'North Korea'),
  CountryDialCode('+65', 'Singapore'),
  CountryDialCode('+60', 'Malaysia'),
  CountryDialCode('+66', 'Thailand'),
  CountryDialCode('+84', 'Vietnam'),
  CountryDialCode('+63', 'Philippines'),
  CountryDialCode('+62', 'Indonesia'),
  CountryDialCode('+855', 'Cambodia'),
  CountryDialCode('+856', 'Laos'),
  CountryDialCode('+673', 'Brunei'),
  CountryDialCode('+976', 'Mongolia'),
  CountryDialCode('+992', 'Tajikistan'),
  CountryDialCode('+993', 'Turkmenistan'),
  CountryDialCode('+994', 'Azerbaijan'),
  CountryDialCode('+995', 'Georgia'),
  CountryDialCode('+996', 'Kyrgyzstan'),
  CountryDialCode('+998', 'Uzbekistan'),
  CountryDialCode('+7', 'Russia / Kazakhstan'),
  CountryDialCode('+374', 'Armenia'),
  CountryDialCode('+375', 'Belarus'),
  CountryDialCode('+380', 'Ukraine'),
  CountryDialCode('+373', 'Moldova'),
  CountryDialCode('+44', 'United Kingdom'),
  CountryDialCode('+353', 'Ireland'),
  CountryDialCode('+33', 'France'),
  CountryDialCode('+49', 'Germany'),
  CountryDialCode('+39', 'Italy'),
  CountryDialCode('+34', 'Spain'),
  CountryDialCode('+351', 'Portugal'),
  CountryDialCode('+31', 'Netherlands'),
  CountryDialCode('+32', 'Belgium'),
  CountryDialCode('+41', 'Switzerland'),
  CountryDialCode('+43', 'Austria'),
  CountryDialCode('+45', 'Denmark'),
  CountryDialCode('+46', 'Sweden'),
  CountryDialCode('+47', 'Norway'),
  CountryDialCode('+358', 'Finland'),
  CountryDialCode('+354', 'Iceland'),
  CountryDialCode('+48', 'Poland'),
  CountryDialCode('+420', 'Czech Republic'),
  CountryDialCode('+421', 'Slovakia'),
  CountryDialCode('+36', 'Hungary'),
  CountryDialCode('+40', 'Romania'),
  CountryDialCode('+359', 'Bulgaria'),
  CountryDialCode('+385', 'Croatia'),
  CountryDialCode('+386', 'Slovenia'),
  CountryDialCode('+381', 'Serbia'),
  CountryDialCode('+382', 'Montenegro'),
  CountryDialCode('+383', 'Kosovo'),
  CountryDialCode('+387', 'Bosnia and Herzegovina'),
  CountryDialCode('+389', 'North Macedonia'),
  CountryDialCode('+355', 'Albania'),
  CountryDialCode('+30', 'Greece'),
  CountryDialCode('+357', 'Cyprus'),
  CountryDialCode('+356', 'Malta'),
  CountryDialCode('+352', 'Luxembourg'),
  CountryDialCode('+377', 'Monaco'),
  CountryDialCode('+1', 'USA / Canada'),
  CountryDialCode('+52', 'Mexico'),
  CountryDialCode('+55', 'Brazil'),
  CountryDialCode('+54', 'Argentina'),
  CountryDialCode('+56', 'Chile'),
  CountryDialCode('+57', 'Colombia'),
  CountryDialCode('+58', 'Venezuela'),
  CountryDialCode('+51', 'Peru'),
  CountryDialCode('+593', 'Ecuador'),
  CountryDialCode('+591', 'Bolivia'),
  CountryDialCode('+595', 'Paraguay'),
  CountryDialCode('+598', 'Uruguay'),
  CountryDialCode('+506', 'Costa Rica'),
  CountryDialCode('+507', 'Panama'),
  CountryDialCode('+502', 'Guatemala'),
  CountryDialCode('+504', 'Honduras'),
  CountryDialCode('+503', 'El Salvador'),
  CountryDialCode('+505', 'Nicaragua'),
  CountryDialCode('+53', 'Cuba'),
  CountryDialCode('+1809', 'Dominican Republic'),
  CountryDialCode('+509', 'Haiti'),
  CountryDialCode('+61', 'Australia'),
  CountryDialCode('+64', 'New Zealand'),
  CountryDialCode('+679', 'Fiji'),
  CountryDialCode('+675', 'Papua New Guinea'),
  CountryDialCode('+27', 'South Africa'),
  CountryDialCode('+234', 'Nigeria'),
  CountryDialCode('+254', 'Kenya'),
  CountryDialCode('+255', 'Tanzania'),
  CountryDialCode('+256', 'Uganda'),
  CountryDialCode('+250', 'Rwanda'),
  CountryDialCode('+251', 'Ethiopia'),
  CountryDialCode('+233', 'Ghana'),
  CountryDialCode('+225', 'Ivory Coast'),
  CountryDialCode('+221', 'Senegal'),
  CountryDialCode('+237', 'Cameroon'),
  CountryDialCode('+243', 'DR Congo'),
  CountryDialCode('+242', 'Congo'),
  CountryDialCode('+244', 'Angola'),
  CountryDialCode('+258', 'Mozambique'),
  CountryDialCode('+260', 'Zambia'),
  CountryDialCode('+263', 'Zimbabwe'),
  CountryDialCode('+267', 'Botswana'),
  CountryDialCode('+264', 'Namibia'),
  CountryDialCode('+268', 'Eswatini'),
  CountryDialCode('+266', 'Lesotho'),
  CountryDialCode('+220', 'Gambia'),
  CountryDialCode('+223', 'Mali'),
  CountryDialCode('+226', 'Burkina Faso'),
  CountryDialCode('+227', 'Niger'),
  CountryDialCode('+228', 'Togo'),
  CountryDialCode('+229', 'Benin'),
  CountryDialCode('+231', 'Liberia'),
  CountryDialCode('+232', 'Sierra Leone'),
  CountryDialCode('+245', 'Guinea-Bissau'),
  CountryDialCode('+224', 'Guinea'),
  CountryDialCode('+238', 'Cape Verde'),
  CountryDialCode('+230', 'Mauritius'),
  CountryDialCode('+248', 'Seychelles'),
  CountryDialCode('+269', 'Comoros'),
  CountryDialCode('+261', 'Madagascar'),
  CountryDialCode('+265', 'Malawi'),
  CountryDialCode('+257', 'Burundi'),
  CountryDialCode('+211', 'South Sudan'),
  CountryDialCode('+236', 'Central African Republic'),
  CountryDialCode('+235', 'Chad'),
  CountryDialCode('+241', 'Gabon'),
  CountryDialCode('+240', 'Equatorial Guinea'),
  CountryDialCode('+239', 'Sao Tome and Principe'),
];
