import Flutter
import UIKit
import Firebase
import FirebaseMessaging
import UserNotifications

/// FIX (9/21 update - "apnsTokenObtained: false, timed out waiting for
/// the APNs token after 10s" - persisted identically across multiple
/// devices/accounts, over both Wi-Fi and 5G, with App ID, APNs Auth
/// Key, entitlements, and provisioning profile all independently
/// verified as correctly configured):
///
/// The previous AppDelegate.swift was the completely bare, unmodified
/// Flutter template - it never called `FirebaseApp.configure()`, never
/// explicitly registered for remote notifications, and relied entirely
/// on Firebase's automatic "method swizzling" to intercept
/// `didRegisterForRemoteNotificationsWithDeviceToken` and forward the
/// raw APNs token to `Messaging.messaging()`. Swizzling is normally
/// silent and automatic, but it is a known, documented source of
/// exactly this failure mode across certain Flutter/Firebase plugin
/// version combinations - the OS-level permission prompt still
/// succeeds (`permissionStatus: authorized`), but the actual device
/// token generated by Apple is never captured/forwarded at all, so
/// `getAPNSToken()` on the Dart side has nothing to return and always
/// times out - identically, on every device, regardless of network.
///
/// FIX: this AppDelegate now explicitly:
///   1. Calls `FirebaseApp.configure()` directly (previously implicit/
///      relied on plugin auto-init timing).
///   2. Sets `UNUserNotificationCenter.current().delegate = self` and
///      requests remote notification registration explicitly via
///      `application.registerForRemoteNotifications()`.
///   3. Overrides `didRegisterForRemoteNotificationsWithDeviceToken` and
///      MANUALLY forwards the raw token to
///      `Messaging.messaging().apnsToken = deviceToken` - this removes
///      any dependency on swizzling working correctly at all.
///   4. Overrides `didFailToRegisterForRemoteNotificationsWithError` to
///      log the real underlying reason via `NSLog`, in case Apple is
///      actually rejecting registration for a specific reason (visible
///      in Xcode's device console / Codemagic's verbose build+test
///      logs, if ever needed for further diagnosis).
@main
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    FirebaseApp.configure()

    if #available(iOS 10.0, *) {
      UNUserNotificationCenter.current().delegate = self
    }
    application.registerForRemoteNotifications()

    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  // Explicit, manual token forwarding - removes any dependency on
  // Firebase's automatic method swizzling working correctly.
  override func application(
    _ application: UIApplication,
    didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data
  ) {
    Messaging.messaging().apnsToken = deviceToken
    super.application(application, didRegisterForRemoteNotificationsWithDeviceToken: deviceToken)
  }

  override func application(
    _ application: UIApplication,
    didFailToRegisterForRemoteNotificationsWithError error: Error
  ) {
    NSLog("EVPair: APNs registration explicitly FAILED with error: \(error.localizedDescription)")
    super.application(application, didFailToRegisterForRemoteNotificationsWithError: error)
  }
}
