// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB3nGQRf6hEwJ4Arnnugi_Za-LSWjboGE',
    appId: '1:193701990892:web:3045cd992fcef5eb6d70c9',
    messagingSenderId: '193701990892',
    projectId: 'evpair-83a96',
    authDomain: 'evpair-83a96.firebaseapp.com',
    storageBucket: 'evpair-83a96.firebasestorage.app',
    measurementId: 'G-QVKSL9SMBZ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvYQ59cdK0A3iKwAxvOIybAhvLwKVxLQQ',
    appId: '1:193701990892:ios:9e3b570677bf64586d70c9',
    messagingSenderId: '193701990892',
    projectId: 'evpair-83a96',
    storageBucket: 'evpair-83a96.firebasestorage.app',
    iosBundleId: 'com.evpairapp.evpair',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvYQ59cdK0A3iKwAxvOIybAhvLwKVxLQQ',
    appId: '1:193701990892:ios:bd325bf18d71a7d06d70c9',
    messagingSenderId: '193701990892',
    projectId: 'evpair-83a96',
    storageBucket: 'evpair-83a96.firebasestorage.app',
    iosBundleId: 'com.example.evpair',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEgGoFVxVKhy51TPblOltb304Z-kLLu_M',
    appId: '1:193701990892:android:82af4edab6f0222e6d70c9',
    messagingSenderId: '193701990892',
    projectId: 'evpair-83a96',
    storageBucket: 'evpair-83a96.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB3nGQRf6hEwJ4Arnnugi_Za-LSWjboGE',
    appId: '1:193701990892:web:1980db948944723e6d70c9',
    messagingSenderId: '193701990892',
    projectId: 'evpair-83a96',
    authDomain: 'evpair-83a96.firebaseapp.com',
    storageBucket: 'evpair-83a96.firebasestorage.app',
    measurementId: 'G-FM33GTN7HD',
  );
}
